[default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.12'
remappings = [
    'ds-test/=lib/ds-test/src/',
    '@openzeppelin/=lib/openzeppelin-contracts',
    '@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradable',
    '@forge-std/=lib/forge-std/src',
]

# See more config options https://github.com/gakonst/foundry/tree/master/config
