name: CI
on: [push]

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Build
        run: |
          forge clean
          forge build --optimize --optimize-runs 1000000

      - name: Run Slither
        uses: crytic/slither-action@v0.1.0
        with:
          target: src/

      - name: Run Tests
        run: |
          forge clean
          forge test --optimize --optimize-runs 1000000 -v
